#!/bin/sh
set -e

CUP_VERBOSE=false

function gather_info() {
	if cat /proc/cmdline | grep -s cros_secure >/dev/null 2>&1; then
		LOADER=depthcharge
	elif [ -d "/sys/firmware/efi" ]; then
		LOADER=efi
	else
		echo "Failed finding out the bootloader"
		exit 1
	fi

	KVER="$(uname -r)"
}

function print_info() {
	gather_info
	echo "Bootloader: $LOADER"
	echo "Kernel version: $KVER"
}

function print_help() {
	case "$1" in
		*)
			printf "$(basename $0): Cadmium Update Program\n"
			printf "Global options:\n"
			printf "\t-v: Enable verbosity\n"
			printf "\t-d: Enable a lot of verbosity\n"
			printf "Subcommands:\n"
			printf "\tinfo: Print gathered machine info\n"
			printf "\thelp: Print help\n"
			printf "\tstatus: Print current machine state\n"
			printf "\tupdate: Update the kernel\n"
		;;
	esac
}

function print_status() {
	true
}

function do_update() {
	true
}

while getopts ':vid' ARG; do
	case "$ARG" in
		v) export CUP_VERBOSE=true ;;
		d) set -x ;;
	esac
done
shift $(expr $OPTIND - 1)

SUBCOMMAND="$1"

case $SUBCOMMAND in
	info) print_info $@ ;;
	help) print_help $@ ;;
	status) print_status $@ ;;
	update) do_update $@ ;;
	"") print_help $@ ;;
	*)
		echo "Error: unknown subcommand: $SUBCOMMAND"
		print_help
	;;
esac
