#!/bin/sh

CUP_VERBOSE=false

function gather_info() {
	if cat /proc/cmdline | grep -s cros_secure >/dev/null 2>&1; then
		LOADER=depthcharge
	elif [ -d "/sys/firmware/efi" ]; then
		LOADER=efi
	else
		echo "Failed finding out the bootloader"
		exit 1
	fi

	KVER="$(uname -r)"
}

function print_info() {
	gather_info
	echo "Bootloader: $LOADER"
	echo "Kernel version: $KVER"
}

function print_help() {
	printf "$(basename $0): Cadmium Update Program\n"
	printf "Options:\n"
	printf "\t-v: Enable verbosity\n"
	printf "Subcommands:\n"
	printf "\tinfo: Print gathered machine info\n"
	printf "\thelp: Print help\n"
}

while getopts ':vi' ARG; do
	echo "$ARG"
	case "$ARG" in
		v) export CUP_VERBOSE=true ;;
	esac
done
shift $(expr $OPTIND - 1)

SUBCOMMAND="$1"

case $SUBCOMMAND in
	info) print_info ;;
	help) print_help ;;
	*)
		echo "Error: unknown subcommand: $SUBCOMMAND"
		print_help
	;;
esac
